# Generated by Django 2.2.5 on 2019-10-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Blog',
        ),
    ]
