# Generated by Django 2.2.5 on 2019-10-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.TextField(),
        ),
    ]
