# Generated by Django 2.2.5 on 2019-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20191009_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.TextField(max_length=250),
        ),
    ]
